version: '3'

services:
  db:
    container_name: mysql_db
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
    ports:
      - "3306:3306"

  web:
    container_name: php_app
    build:
      context: ./web
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./web:/var/www/html

  mail:
    container_name: mail_server
    image: boky/postfix
    restart: always
    environment:
      - ALLOWED_SENDER_DOMAINS=example.com
    ports:
      - "25:25"

